name: Test
on:
  workflow_dispatch:
  schedule:
    - cron: '52 11 * * *'
  push:
    branches:
      - main
      - stable
jobs:
  triggered:
    if: github.repository_owner == 'csomh' && github.event.schedule == null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.event.schedule != null
      - name: cat
        run: |
          cat file
  scheduled:
    if: github.repository_owner == 'csomh' && github.event.schedule != null
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          branch:
            - main
            - stable
    steps:
      - uses: actions/checkout@v3
        if: github.event.schedule != null
        with:
          ref: ${{ matrix.branch }}
      - name: cat
        run: |
          cat file
