name: Test
on:
  workflow_dispatch:
  schedule:
    - cron: "32 16 * * *"
  push:
    branches:
      - main
      - stable
jobs:
  test:
    if: github.repository_owner == 'csomh'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cat
        run: |
          cat file
