name: Test
on:
  workflow_dispatch:
  schedule:
    - cron: '37 11 * * *'
    - cron: '38 11 * * *'
  push:
    branches:
      - main
      - stable
jobs:
  test:
    if: github.repository_owner == 'csomh'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: github.event.schedule == '37 11 * * *'
        with:
          ref: main
      - uses: actions/checkout@v3
        if: github.event.schedule == '38 11 * * *'
        with:
          ref: stable
      - uses: actions/checkout@v3
        if: github.event.schedule == null
      - name: cat
        run: |
          cat file
